server:
  port: 3000
  servlet:
    context-path: /api/v1

app:
  base-url: http://localhost:3000
  verify-email-url: http://localhost:3000/api/v1/auth/verify-email

spring:
  application:
    name: restapi

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:3000/api/v1/login/oauth2/code/google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

  #  file-size-threshold: Quy định ngưỡng dung lượng file được lưu tạm trong bộ nhớ
  #  (RAM) trước khi ghi ra ổ cứng (temporary file).
  #  Nếu file < 2 KB → giữ trong bộ nhớ.
  #  Nếu file ≥ 2 KB → Spring ghi ra file tạm trên disk (thường trong thư mục hệ thống như /tmp).

  jackson:
    time-zone: UTC

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        format-sql: true
        jdbc:
          time_zone: UTC
  
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    #    .org:
    #      springframework:
    #        security:
    #          web:
    #            FilterChainProxy: TRACE
    software.amazon.awssdk: INFO
    root: warn
    com:
      example:
        librarymanagement:
          logger: INFO

  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

jwt:
  access:
    secret-key: ${JWT_ACCESS_TOKEN_SECRET}
    expiration-time: ${JWT_ACCESS_TOKEN_EXPIRES}
  refresh:
    secret-key: ${JWT_REFRESH_TOKEN_SECRET}
    expiration-time: ${JWT_REFRESH_TOKEN_EXPIRES}

verify:
  token:
    mail: 86400000
    reset-password: 30000
    change-email: 86400000

cloud:
  aws:
    region: ap-southeast-1
    buckets:
      main: chatapp-internal-test
    folders:
      images: images/
      audio: audio/
      video: video/
      images-sub-folders:
        users: images/users/
# dzrp onpk xegq annk
# LibraryHT

